### ISSUE TITLE
support stake/unstake

### ISSUE THREAD

**Issue by crazydevlegend** [crazydevlegend/multi-sig-app#5]
* **I'm submitting a**

  - [ ] Bug report
  - [x] Feature request
  - [ ] Support request
  - [ ] Other

Currently, it shows free balances only.
Let's add features to support stake/unstake.

- Accounts
<img width="2207" alt="image" src="https://github.com/user-attachments/assets/892ef7b8-8ad8-4db4-b3fd-cecc0a3d880f">

- Multi-sig Account
<img width="1361" alt="image" src="https://github.com/user-attachments/assets/6dac8731-d3be-4c1b-b983-06cbf60ad0fe">

**Comment by ethsdev** [comment]
You mean adding stake/unstake button next send button?
If so, why Extrinsics page is needed? and these are not so simple for adding there.  It has hotkey, amount, and call data.
And I think it make UI not looks good.

**Comment by crazydevlegend** [comment]
> You mean adding stake/unstake button next send button? If so, why Extrinsics page is needed? and these are not so simple for adding there. It has hotkey, amount, and call data. And I think it make UI not looks good.

You can redirect to the extrinsic page with `stake`/`unstake` selected and the appropriate account

**Comment by solthereum** [comment]
I submitted new PR for staked amount. It works well on westend testnet.

**Comment by crazydevlegend** [comment]
let's close this as it's doable on `extrinsics` page
