### ISSUE TITLE
show token balance in address book page

### ISSUE THREAD

**Issue by crazydevlegend** [crazydevlegend/multi-sig-app#6]
* **I'm submitting a ...**
  - [ ] Bug report
  - [x] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**
In `Address Book`, each contact should show token balance (and stake amount as well)  next to the address column

- Current
<img width="1722" alt="image" src="https://github.com/user-attachments/assets/3bc08e98-459a-4136-91a5-3249eebbca2b">

- Expected
<img width="1684" alt="image" src="https://github.com/user-attachments/assets/dbb3116e-1ea2-407a-bfd5-b6bb2fa72b2d">

* **Please tell us about your environment:**
  - [ ] Node.js
  - [x] Browser
  - [ ] Other (limited support for other environments)

**Comment by ethsdev** [comment]
I will do this on next PR

**Comment by ethsdev** [comment]
done!
