### ISSUE TITLE
add footer with company copyright

### ISSUE THREAD

**Issue by crazydevlegend** [crazydevlegend/multi-sig-app#7]
* **I'm submitting a ...**

  - [ ] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [x] Other

* **What is the current behavior and expected behavior?**
Current page doesn't have a footer - let's add one that shows copyright

* **Please tell us about your environment:**
  - [ ] Node.js
  - [x] Browser
  - [ ] Other (limited support for other environments)

**Comment by ethsdev** [comment]
Do you have a design for copyright?

**Comment by crazydevlegend** [comment]
> Do you have a design for copyright?

Designer is working on it - will have an update after a few hours

**Comment by crazydevlegend** [comment]
![image](https://github.com/user-attachments/assets/09d7ec01-28b8-41ab-a34e-f1f08b1d0b77)
@solthereum here's the footer design

**Comment by ethsdev** [comment]
done!
